server:
  port: 8084
  servlet:
    context-path: /

application:
  title: Risk Management System
  version: 1.0.0


patientms:
  name: ${PATIENT_MS_NAME:patient-ms}
  url: ${PATIENT_MS_URL:http://localhost:8081}

notems:
  name: ${NOTE_MS_NAME:note-ms}
  url: ${NOTE_MS_URL:http://localhost:8083}

spring:
  application:
    name: note-ms
  main:
    banner-mode: console
  banner:
    charset: UTF-8
    location: banner.txt

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000