@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

LAYOUT_LEFT_RIGHT()

title Medical Assessment Platform - C4 Container

' ========================
' STYLE
' ========================

UpdateElementStyle(person, $bgColor="#6CB5C3", $borderColor="#000000", $fontColor="#12288A")
UpdateElementStyle(containerDb, $bgColor="#247F2A", $borderColor="#247F2A", $fontColor="#247F2A")
Person(organizer, "Organizer")
Person(doctor, "Doctor")


System_Boundary(system, "Medical Assessment Platform") {

    Container(front, "front-ms", "Frontend", "medical UI")

    Container(gateway, "gateway-ms", "Spring Cloud Gateway", "API Gateway")

    Container(patient, "patient-ms", "Spring Boot + JPA", "Patient management")
    Container(notes, "notes-ms", "Spring Boot + MongoDB", "Note management")
    Container(assessment, "risk-assessment-ms", "Spring Boot", "Risk assessment calculation")

    ContainerDb(patientDb, "Patient DB", "PostgreSQL")
    ContainerDb(notesDb, "Notes DB", "MongoDB")
}

Rel(organizer, front, "Use")
Rel(doctor, front, "Use")

Rel(front, gateway, "API calls")

Rel(gateway, patient, "Route")
Rel(gateway, notes, "Route")
Rel(gateway, assessment, "Route")

Rel(patient, patientDb, "CRUD")
Rel(notes, notesDb, "CRUD")

Rel(assessment, patient, "REST API")
Rel(assessment, notes, "REST API")


@enduml