@startuml

title Gateway-MS - Security & Auth Architecture

skinparam classAttributeIconSize 0
package "Gateway-MS" {

    class "Spring Cloud Gateway Runtime" as SpringCloudGateway {
    }

   class "Route Configuration (Spring Cloud Gateway YAML)" as GatewayRoutes {
       + /patients/**  → patient-ms
       + /notes/**     → note-ms
       + /risk/**      → risk-ms
   }
}

package "Front"{
}

package "Auth-MS"{
}

package "Patient-MS" {
}

package "Note-MS" {
}

package "Risk-MS" {
}



' =======================
' RELATIONS
' =======================
"Front" --> SpringCloudGateway
SpringCloudGateway --> GatewayRoutes
SpringCloudGateway --> "Auth-MS"
SpringCloudGateway --> "Patient-MS"
SpringCloudGateway --> "Note-MS"
SpringCloudGateway --> "Risk-Assessment-MS"
"Front" <-- SpringCloudGateway
SpringCloudGateway <-- "Auth-MS"
SpringCloudGateway <-- "Patient-MS"
SpringCloudGateway <-- "Note-MS"
SpringCloudGateway <-- "Risk-MS"

@enduml