server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: patient-ms

  main:
    banner-mode: console
  banner:
    charset: UTF-8

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        default_schema: patients

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: patients
    contexts: local

  sql:
    init:
      platform: postgres



springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: ERROR
    com.medical.assessment.patientms: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.boot.autoconfigure.liquibase: TRACE
    org.springframework.jdbc: DEBUG
    springframework:
      boot:
        autoconfigure:
          postgresql: INFO
    liquibase: TRACE

    org.springframework.core.env: TRACE