
server:
  port: 8080

application:
  title: Gateway
  version: 1.0.0

spring:
  application:
    name: gateway
  main:
    banner-mode: console
  banner:
    charset: UTF-8
    location: banner.txt
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-ms
              uri : http://localhost:8081
              predicates:
                - Path=/patient/**
            - id: auth-ms
              uri : http://localhost:8082
              predicates:
                - Path=/auth/**
            - id: note-ms
              uri : http://localhost:8083
              predicates:
                - Path=/notes/**
