
server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-ms
              uri : http://localhost:8081
              predicates:
                - Path=/patient/**
            - id: auth-ms
              uri : http://localhost:8082
              predicates:
                - Path=/auth/**
