server:
    port: 8083
    servlet:
        context-path: /
application:
    title: Note Management System
    version: 1.0.0
spring:
    application:
        name: note-ms
    main:
        banner-mode: console
    banner:
        charset: UTF-8
        location: banner.txt
    data:
        mongodb:
            uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/notedb?authSource=admin
            database: notedb