package com.medical.assessment.patientms.controller.authentification;

import com.medical.assessment.patientms.authentification.api.AuthentificationApi;
import com.medical.assessment.patientms.authentification.model.AuthTokenResponse;
import com.medical.assessment.patientms.security.jwt.JwtService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RestController;

/*FIXME: Temporary authentication controller for testing purposes.
 * This controller is ONLY used for local development and testing.
 * Once the API Gateway is implemented:
 * - This controller MUST be removed
 * - JWT tokens will be generated by the Gateway (not this service)
 * Security note:
 * - The role is provided by the client
 * - This is NOT secure
 */

@RestController
@RequiredArgsConstructor
@Slf4j
public class AuthController implements AuthentificationApi {
    private final JwtService jwtService;

    @Override
    public ResponseEntity<AuthTokenResponse> getAuthToken(final String username, final String role) {
        log.info("getting auth token for user {} with role {}", username, role);
        final String token = jwtService.generateToken(username, role);
        final AuthTokenResponse authTokenResponse = new AuthTokenResponse();
        authTokenResponse.setToken(token);
        return ResponseEntity.ok(authTokenResponse);
    }
}
